IF OBJECT_ID('DeleteAllPrintReportMessage', 'P') IS NOT NULL
BEGIN
	DROP PROCEDURE DeleteAllPrintReportMessage
END
GO

CREATE PROCEDURE DeleteAllPrintReportMessage
AS
BEGIN
	
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT
	BEGIN TRANSACTION

	BEGIN TRY
	
		DELETE FROM [dbo].[PrintReportMessage]

		COMMIT TRANSACTION

	END TRY

	BEGIN CATCH
		
		ROLLBACK TRANSACTION
		DECLARE @errorMsg NVARCHAR(2048) = ERROR_MESSAGE()
		RAISERROR(@errorMsg, 16, 1)

	END CATCH
	
END