IF OBJECT_ID('DeletePrintReportMessageById', 'P') IS NOT NULL
BEGIN
	DROP PROCEDURE DeletePrintReportMessageById
END
GO

CREATE PROCEDURE DeletePrintReportMessageById
	@messageId UNIQUEIDENTIFIER
AS
BEGIN

	SET TRANSACTION ISOLATION LEVEL SNAPSHOT
	BEGIN TRANSACTION

	BEGIN TRY
	
		DELETE FROM [dbo].[PrintReportMessage]
		WHERE [PRM_MessageId] = @messageId

		COMMIT TRANSACTION

	END TRY

	BEGIN CATCH
		
		ROLLBACK TRANSACTION
		DECLARE @errorMsg NVARCHAR(2048) = ERROR_MESSAGE()
		RAISERROR(@errorMsg, 16, 1)

	END CATCH
	
END