IF OBJECT_ID('[dbo].[SqlConfig]', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[SqlConfig] (
		[SC_SqlConfigId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_SqlConfig_SqlConfigId] DEFAULT(NEWID()),
		[SC_Id] VARCHAR(50) NOT NULL,
		[SC_DatabaseId] VARCHAR(20) NOT NULL,
		[SC_Query] NVARCHAR(MAX) NOT NULL,

		CONSTRAINT [PK_dbo.SqlConfig] PRIMARY KEY CLUSTERED ([SC_SqlConfigId])
	);
END