IF OBJECT_ID('[dbo].[DeleteSqlConfigByIds]', 'P') IS NOT NULL
BEGIN
	DROP PROCEDURE [dbo].[DeleteSqlConfigByIds]
END
GO

CREATE PROCEDURE [dbo].[DeleteSqlConfigByIds]
	@sqlConfigIds NVARCHAR(MAX)
AS
BEGIN	
	IF @@TRANCOUNT = 0
	BEGIN
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT
	END

	BEGIN TRANSACTION

	BEGIN TRY
	
		DECLARE @temp TABLE (
			SqlConfigId UNIQUEIDENTIFIER
		);
		
		INSERT INTO @temp
		SELECT value FROM STRING_SPLIT(@sqlConfigIds, ','); 

		DELETE FROM SqlConfig
		WHERE SC_SqlConfigId IN (
			SELECT * FROM @temp
		)

		COMMIT TRANSACTION

	END TRY

	BEGIN CATCH
		
		ROLLBACK TRANSACTION
		DECLARE @errorMsg NVARCHAR(2048) = ERROR_MESSAGE()
		RAISERROR(@errorMsg, 16, 1)

	END CATCH
END