IF DB_ID('ReportPrinter') IS NULL
BEGIN
	CREATE DATABASE ReportPrinter
END

ALTER DATABASE ReportPrinter
SET READ_COMMITTED_SNAPSHOT ON
GO

ALTER DATABASE ReportPrinter
SET ALLOW_SNAPSHOT_ISOLATION ON
GO